name: Publish Docker image

on:
  push:
    branches: ['main']
    tags: ['v*'] # Запускается при создании тега, начинающегося с 'v' (например, v1.0.0)

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version from tag
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: bolgov0zero/ads-panel
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Set outputs for notify
        id: outputs
        run: |
          echo "tags=${{ steps.meta.outputs.tags || 'latest' }}" >> $GITHUB_OUTPUT

  notify:
    runs-on: ubuntu-latest
    needs: build-and-push  # Ждёт завершения основной job
    if: always()  # Запускается всегда (success, failure, cancelled)
    steps:
      - name: Send Telegram notification
        uses: up9cloud/action-notify@master
        env:
          GITHUB_JOB_STATUS: ${{ needs.build-and-push.result }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_TEMPLATE_CONTENT: |
            🐳 Docker image для bolgov0zero/ads-panel ${{ github.ref_name || 'latest' }} завершён!
            Статус: ${{ needs.build-and-push.result == 'success' && '✅ Успех' || needs.build-and-push.result == 'failure' && '❌ Ошибка' || '⚠️ Отмена' }}
            Тег: ${{ needs.build-and-push.outputs.tags || 'latest' }}
            Логи: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            Репозиторий: https://hub.docker.com/r/bolgov0zero/ads-panel/tags
