name: Ads Panel Docker Builder

on:
  workflow_dispatch:
    branches: ['main']
  push:
    branches: ['main', 'dev']
    paths:
      - 'panel_files/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ github.ref_name == 'main' && 'bolgov0zero/ads-panel:latest' || 'bolgov0zero/ads-panel:dev' }}
  notify:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: always()
    steps:
      - name: Send Telegram notification
        uses: up9cloud/action-notify@master
        env:
          GITHUB_JOB_STATUS: ${{ needs.build-and-push.result }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_TEMPLATE_CONTENT: |
            🐳 Публикация образа Ads Panel завершёна!
            Статус: ${{ needs.build-and-push.result == 'success' && '✅ Успех' || needs.build-and-push.result == 'failure' && '❌ Ошибка' || '⚠️ Отмена' }}
            Коммит: ${{ github.event.head_commit.message }}
            Версия: ${{ github.ref_name == 'main' && 'latest' || 'dev' }}
